### ISSUE TITLE
bug:  full permissions are not needed 

### ISSUE THREAD

**Issue by charleslavon** [near/boilerplate-template-rs#4]
# Bug Report

Full permissions are not needed by this app. Function call should suffice here. We should request the minimum permissions whenever possible.  
<img width="790" alt="Screen Shot 2023-01-09 at 5 19 18 PM" src="https://user-images.githubusercontent.com/1915116/211419900-f5b64608-bee8-4414-a539-ee841f7a1648.png">

**PROJECT_NAME version:**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by shelegdmitriy** [comment]
@charleslavon I think this issue is already fixed
