### ISSUE TITLE
bug: unable to set a message 

### ISSUE THREAD

**Issue by charleslavon** [near/boilerplate-template-rs#6]
# Bug Report

When I attempt to sign into a testnet wallet I'm unable to complete the transaction due to the following error. @shelegdmitriy pelase test this on [this repo](https://github.com/charleslavon/cg-rs-template) which I created from the template-rs

<img width="1338" alt="Screen Shot 2023-01-10 at 5 05 18 PM" src="https://user-images.githubusercontent.com/1915116/211672657-ade0f007-8173-4209-9c28-e99fd80631bb.png">

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by shelegdmitriy** [comment]
@charleslavon I can't reproduce this one.I cloned your repository, followed [this steps](https://github.com/charleslavon/cg-rs-template#installation) and everything works as well
